server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hospital-db-do-user-14558489-0.b.db.ondigitalocean.com:25060/user_service_db
    username: doadmin
    password: AVNS_ZsEHpELLbPwTvabmXJN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect


services:
  notification-url: http://NOTIFICATION-SERVICE/notification
  get-working-days: http://HYBRID-BOOKING-SERVICE/hybrid-booking/send-working-days-of-doctor
  get-hospital : http://HOSPITAL-SERVICE/hospital/send-id
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://134.209.20.129:8761/eureka/}
    instance:
      preferIpAddress: true


jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
  access:
    expiry: 86400000
  refresh:
    expiry: 604800000