package com.example.userservice.domain.entity.doctor;

public enum DoctorSpecialty {
    GENERAL_MEDICINE,
    SURGERY,
    PEDIATRICS,
    OBSTETRICS_AND_GYNECOLOGY,
    ORTHOPEDICS,
    CARDIOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    DERMATOLOGY,
    GASTROENTEROLOGY,
    UROLOGY,
    PSYCHIATRY,
    ANESTHESIOLOGY,
    RADIOLOGY,
    EMERGENCY_MEDICINE,
    PATHOLOGY,
    NEPHROLOGY,
    PULMONOLOGY,
    ENDOCRINOLOGY

}
